"""Got rid of description on bookings model

Revision ID: 616225d5533c
Revises: debdbbc606ad
Create Date: 2022-08-03 18:14:28.086172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616225d5533c'
down_revision = 'debdbbc606ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'description')
    op.alter_column('spots', 'address',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('spots', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spots', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('spots', 'address',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.add_column('bookings', sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
